samples:
  T_14: /home/skevin/rb_pipeline/output/gatk/14-T_1_recalibrated.bam
  C_14: /home/skevin/rb_pipeline/output/gatk/14-CL_1_recalibrated.bam
  N_14: /home/skevin/rb_pipeline/output/gatk/14-N_1_recalibrated.bam
  T_20: /home/skevin/rb_pipeline/output/gatk/20-T_1_recalibrated.bam
  C_20: /home/skevin/rb_pipeline/output/gatk/20-CL_1_recalibrated.bam
  N_20: /home/skevin/rb_pipeline/output/gatk/20-N_1_recalibrated.bam
  T_24: /home/skevin/rb_pipeline/output/gatk/24-T_1_recalibrated.bam
  C_24: /home/skevin/rb_pipeline/output/gatk/24-CL_1_recalibrated.bam
  N_24: /home/skevin/rb_pipeline/output/gatk/24-N_1_recalibrated.bam
  T_28: /home/skevin/rb_pipeline/output/gatk/28-T_1_recalibrated.bam
  C_28: /home/skevin/rb_pipeline/output/gatk/28-CL_1_recalibrated.bam
  N_28: /home/skevin/rb_pipeline/output/gatk/28-N_1_recalibrated.bam
  T_29: /home/skevin/rb_pipeline/output/gatk/29-T_1_recalibrated.bam
  C_29: /home/skevin/rb_pipeline/output/gatk/29-CL_1_recalibrated.bam
  N_29: /home/skevin/rb_pipeline/output/gatk/29-N_1_recalibrated.bam
  T_31: /home/skevin/rb_pipeline/output/gatk/31-T_1_recalibrated.bam
  C_31: /home/skevin/rb_pipeline/output/gatk/31-CL_1_recalibrated.bam
  N_31: /home/skevin/rb_pipeline/output/gatk/31-N_1_recalibrated.bam
  T_33: /home/skevin/rb_pipeline/output/gatk/33-T_1_recalibrated.bam
  C_33: /home/skevin/rb_pipeline/output/gatk/33-CL_1_recalibrated.bam
  N_33: /home/skevin/rb_pipeline/output/gatk/33-N_1_recalibrated.bam
  T_41: /home/skevin/rb_pipeline/output/gatk/41-T_1_recalibrated.bam
  C_41: /home/skevin/rb_pipeline/output/gatk/41-CL_1_recalibrated.bam
  N_41: /home/skevin/rb_pipeline/output/gatk/41-N_1_recalibrated.bam
  T_43: /home/skevin/rb_pipeline/output/gatk/43-T_1_recalibrated.bam
  C_43: /home/skevin/rb_pipeline/output/gatk/43-CL_1_recalibrated.bam
  N_43: /home/skevin/rb_pipeline/output/gatk/43-N_1_recalibrated.bam
  T_46: /home/skevin/rb_pipeline/output/gatk/46-T_1_recalibrated.bam
  C_46: /home/skevin/rb_pipeline/output/gatk/46-CL_1_recalibrated.bam
  N_46: /home/skevin/rb_pipeline/output/gatk/46-N_1_recalibrated.bam
  T_48: /home/skevin/rb_pipeline/output/gatk/48-T_1_recalibrated.bam
  C_48: /home/skevin/rb_pipeline/output/gatk/48-CL_1_recalibrated.bam
  N_48: /home/skevin/rb_pipeline/output/gatk/48-N_1_recalibrated.bam
  T_49: /home/skevin/rb_pipeline/output/gatk/49-T_1_recalibrated.bam
  C_49: /home/skevin/rb_pipeline/output/gatk/49-CL_1_recalibrated.bam
  N_49: /home/skevin/rb_pipeline/output/gatk/49-N_1_recalibrated.bam

pairings:
  T_14:  N_14
  T_20:  N_20
  T_24:  N_24
  T_28:  N_28
  T_29:  N_29
  T_31:  N_31
  T_33:  N_33
  T_41:  N_41
  T_43:  N_43
  T_46:  N_46
  T_48:  N_48
  T_49:  N_49
  C_14:  N_14
  C_20:  N_20
  C_24:  N_24
  C_28:  N_28
  C_29:  N_29
  C_31:  N_31
  C_33:  N_33
  C_41:  N_41
  C_43:  N_43
  C_46:  N_46
  C_48:  N_48
  C_49:  N_49
